version: 2.1
orbs:
  python: circleci/python@2.0.3
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/python:3.13.5
    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      # - run:
      #     name: "Install dependencies"
      #     command: "pip install -r requirements.txt"
  lint:
    docker:
      - image: cimg/python:3.13.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: "install pylint"
          command: "pip install pylint"
      - run:
          name: "Lint all"
          command: "find . -name '*.py' | xargs pylint"


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  default:
    jobs:
      - build
      - lint:
          requires: 
            - build